config:
  modules:
    http_2xx:
      http:
        no_follow_redirects: false
        preferred_ip_protocol: ip4
        tls_config:
          insecure_skip_verify: true
        valid_http_versions:
        - HTTP/1.1
        - HTTP/2
      prober: http
      timeout: 5s
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - prometheus-blackbox-exporter.192.168.73.165.omg.howdoi.website
